version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://jsonplaceholder.typicode.com
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules